services:
  pinnule:
    image: ghcr.io/nikon1977/pinnule:latest
    container_name: pinnule
    restart: unless-stopped

    ports:
      - "4000:4000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pinnule_data:/app/data

volumes:
  pinnule_data:
